// * Admin
export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const LOAD_ADMIN = "LOAD_ADMIN";
export const EDIT_ADMIN = "EDIT_ADMIN";
export const ADMIN_ERROR = "ADMIN_ERROR";
export const ADMIN_MESSAGE = "ADMIN_MESSAGE";
export const ADMIN_LOADING = "ADMIN_LOADING";
export const CLEAR_ADMIN_ERROR = "RESET_ADMIN_ERROR";

// * Enquiry
export const LIST_ENQUIRY = "LIST_ENQUIRY";
export const SELECT_ENQUIRY = "SELECT_ENQUIRY";
export const CLEAR_ENQUIRY_LIST = "CLEAR_ENQUIRY_LIST";
export const ENQUIRY_ERROR = "ENQUIRY_ERROR";
export const ENQUIRY_MESSAGE = "ENQUIRY_MESSAGE";
export const ENQUIRY_LOADING = "ENQUIRY_LOADING";
export const CLEAR_ENQUIRY_ERROR = "CLEAR_ENQUIRY_ERROR";

// * Doctor
export const LOGIN_DOCTOR = "LOGIN_DOCTOR";
export const LOAD_DOCTOR = "LOAD_DOCTOR";
export const LOAD_DOCTOR_COMPLETE = "LOAD_DOCTOR_COMPLETE";
export const EDIT_DOCTOR = "EDIT_DOCTOR";
export const LIST_DOCTOR = "LIST_DOCTOR";
export const CLEAR_DOCTOR_LIST = "CLEAR_DOCTOR_LIST";
export const SELECT_DOCTOR = "SELECT_DOCTOR";
export const DOCTOR_ERROR = "DOCTOR_ERROR";
export const DOCTOR_MESSAGE = "DOCTOR_MESSAGE";
export const DOCTOR_LOADING = "DOCTOR_LOADING";
export const CLEAR_DOCTOR_ERROR = "CLEAR_DOCTOR_ERROR";

// * User
export const LOAD_USER = "LOAD_USER";
export const INCOMPLETE_PROFILE = "INCOMPLETE_PROFILE";
export const EDIT_USER = "EDIT_USER";
export const GET_CHATROOMS = "GET_CHATROOMS";
export const LIST_USER = "LIST_USER";
export const CLEAR_USER_LIST = "CLEAR_USER_LIST";
export const SELECT_USER = "SELECT_USER";
export const SELECT_CHATROOM_USER = "SELECT_CHATROOM_USER";
export const USER_GET_MESSAGES = "USER_GET_MESSAGES";
export const CLEAR_USER_CHATROOM = "CLEAR_USER_CHATROOM";
export const USER_ERROR = "USER_ERROR";
export const USER_MESSAGE = "USER_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_CHATROOM_LOADING = "USER_CHATROOM_LOADING";
export const CLEAR_USER_ERROR = "CLEAR_USER_ERROR";
