// * Admin
export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const LOAD_ADMIN = "LOAD_ADMIN";
export const LOGOUT_ADMIN = "LOGOUT_ADMIN";
export const EDIT_ADMIN = "EDIT_ADMIN";
export const ADMIN_GET_CHATROOMS = "ADMIN_GET_CHATROOMS";
export const SELECT_CHATROOM_ADMIN = "SELECT_CHATROOM_ADMIN";
export const ADMIN_GET_MESSAGES = "ADMIN_GET_MESSAGES";
export const APPEND_ADMIN_MESSAGE = "APPEND_ADMIN_MESSAGE";
export const CLEAR_ADMIN_CHATROOM = "CLEAR_ADMIN_CHATROOM";
export const ADMIN_ERROR = "ADMIN_ERROR";
export const ADMIN_MESSAGE = "ADMIN_MESSAGE";
export const ADMIN_LOADING = "ADMIN_LOADING";
export const ADMIN_CHATROOM_LOADING = "ADMIN_CHATROOM_LOADING";
export const CLEAR_ADMIN_ERROR = "RESET_ADMIN_ERROR";
export const CLEAR_ADMIN_ACTIVE_CHATROOM = "CLEAR_ADMIN_ACTIVE_CHATROOM";
export const CLEAR_UNREAD_MESSAGES_ACTIVE_ADMIN =
  "CLEAR_UNREAD_MESSAGES_ACTIVE_ADMIN";
export const CLEAR_UNREAD_MESSAGES_ADMIN = "CLEAR_UNREAD_MESSAGES_ADMIN";
export const ADD_QUESTION_TO_QUESTION_SET = "ADD_QUESTION_TO_QUESTION_SET";
export const GET_ADMIN_QUESTION_SET = "GET_ADMIN_QUESTION_SET";

// * Enquiry
export const LIST_ENQUIRY = "LIST_ENQUIRY";
export const SELECT_ENQUIRY = "SELECT_ENQUIRY";
export const CLEAR_ENQUIRY_LIST = "CLEAR_ENQUIRY_LIST";
export const ENQUIRY_ERROR = "ENQUIRY_ERROR";
export const ENQUIRY_MESSAGE = "ENQUIRY_MESSAGE";
export const ENQUIRY_LOADING = "ENQUIRY_LOADING";
export const CLEAR_ENQUIRY_ERROR = "CLEAR_ENQUIRY_ERROR";

// * Doctor
export const LOGIN_DOCTOR = "LOGIN_DOCTOR";
export const LOAD_DOCTOR = "LOAD_DOCTOR";
export const LOAD_DOCTOR_COMPLETE = "LOAD_DOCTOR_COMPLETE";
export const EDIT_DOCTOR = "EDIT_DOCTOR";
export const LIST_DOCTOR = "LIST_DOCTOR";
export const CLEAR_DOCTOR_LIST = "CLEAR_DOCTOR_LIST";
export const SELECT_DOCTOR = "SELECT_DOCTOR";
export const DOCTOR_ERROR = "DOCTOR_ERROR";
export const DOCTOR_MESSAGE = "DOCTOR_MESSAGE";
export const DOCTOR_LOADING = "DOCTOR_LOADING";
export const CLEAR_DOCTOR_ERROR = "CLEAR_DOCTOR_ERROR";
export const DOCTOR_GET_CHATROOMS = "DOCTOR_GET_CHATROOMS";
export const DOCTOR_CHATROOM_LOADING = "DOCTOR_CHATROOM_LOADING";
export const SELECT_CHATROOM_DOCTOR = "SELECT_CHATROOM_DOCTOR";
export const CLEAR_UNREAD_MESSAGES_DOCTOR = "CLEAR_UNREAD_MESSAGES_DOCTOR";
export const APPEND_DOCTOR_MESSAGE = "APPEND_DOCTOR_MESSAGE";
export const CLEAR_DOCTOR_CHATROOM = "CLEAR_DOCTOR_CHATROOM";
export const DOCTOR_GET_MESSAGES = "DOCTOR_GET_MESSAGES";
export const DOCTOR_ADD_QUESTION_TO_QUESTION_SET =
  "DOCTOR_ADD_QUESTION_TO_QUESTION_SET";
export const GET_DOCTOR_QUESTION_SET = "GET_DOCTOR_QUESTION_SET";

// * User
export const LOAD_USER = "LOAD_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const INCOMPLETE_PROFILE = "INCOMPLETE_PROFILE";
export const EDIT_USER = "EDIT_USER";
export const GET_CHATROOMS = "GET_CHATROOMS";
export const LIST_USER = "LIST_USER";
export const CLEAR_USER_LIST = "CLEAR_USER_LIST";
export const SELECT_USER = "SELECT_USER";
export const SELECT_CHATROOM_USER = "SELECT_CHATROOM_USER";
export const USER_GET_MESSAGES = "USER_GET_MESSAGES";
export const APPEND_USER_MESSAGE = "APPEND_USER_MESSAGE";
export const CLEAR_USER_CHATROOM = "CLEAR_USER_CHATROOM";
export const USER_ERROR = "USER_ERROR";
export const USER_MESSAGE = "USER_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_CHATROOM_LOADING = "USER_CHATROOM_LOADING";
export const CLEAR_USER_ERROR = "CLEAR_USER_ERROR";
export const CLEAR_UNREAD_MESSAGES = "CLEAR_UNREAD_MESSAGES";
export const CLEAR_UNREAD_MESSAGES_ACTIVE = "CLEAR_UNREAD_MESSAGES_ACTIVE";
export const CLEAR_ACTIVE_CHATROOM = "CLEAR_ACTIVE_CHATOOM";
export const LIST_USER_CALL_HISTORY = "LIST_USER_CALL_HISTORY";
export const LIST_USER_CALL_HISTORY_ERROR = "LIST_USER_CALL_HISTORY_ERROR";
export const CLEAR_CALL_HISTORY_LIST = "CLEAR_CALL_HISTORY_LIST";
export const GET_QUESTION_SET = "GET_QUESTION_SET";

// * Chatroom
export const SHOW_DRAWER = "SHOW_DRAWER";
